### ISSUE TITLE
Problem running btcpayserver.org locally

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver.org#193]
Getting this when doing `npm start`, but seems netlify complies it so could be my local enviroment.

```
npm start

> btcpayserver.org@1.0.0 start /Users/p/Downloads/btcpayserver.org
> npm-run-all clean -p start:*


> btcpayserver.org@1.0.0 clean /Users/p/Downloads/btcpayserver.org
> rimraf dist && mkdir -p dist


> btcpayserver.org@1.0.0 start:scripts /Users/p/Downloads/btcpayserver.org
> onchange -i -k 'src/js/**/*' -- npm run build:scripts


> btcpayserver.org@1.0.0 start:static /Users/p/Downloads/btcpayserver.org
> onchange -i -k 'src/static/**/*' -- npm run build:static


> btcpayserver.org@1.0.0 start:styles /Users/p/Downloads/btcpayserver.org
> onchange -i -k 'src/css/**/*' -- npm run build:styles


> btcpayserver.org@1.0.0 start:vtt /Users/p/Downloads/btcpayserver.org
> onchange -i -k 'src/vtt/**/*' 'tasks/{render_vtt,util}.js' -- npm run build:vtt


> btcpayserver.org@1.0.0 start:serve /Users/p/Downloads/btcpayserver.org
> browser-sync start --no-open --watch --server dist


> btcpayserver.org@1.0.0 start:html /Users/p/Downloads/btcpayserver.org
> onchange -i -k 'src/{html,json}/**/*' 'tasks/{render_html,util}.js' -- npm run build:html


> btcpayserver.org@1.0.0 build:static /Users/p/Downloads/btcpayserver.org
> cp -rT src/static dist


> btcpayserver.org@1.0.0 build:html /Users/p/Downloads/btcpayserver.org
> node tasks/render_html.js


> btcpayserver.org@1.0.0 build:styles /Users/p/Downloads/btcpayserver.org
> cp -r src/css dist


> btcpayserver.org@1.0.0 build:vtt /Users/p/Downloads/btcpayserver.org
> node tasks/render_vtt.js


> btcpayserver.org@1.0.0 build:scripts /Users/p/Downloads/btcpayserver.org
> cp -r src/js dist

cp: illegal option -- T
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-aclpSsvXx] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-aclpSsvXx] source_file ... target_directory
npm ERR! code ELIFECYCLE
npm ERR! errno 64
npm ERR! btcpayserver.org@1.0.0 build:static: `cp -rT src/static dist`
npm ERR! Exit status 64
npm ERR! 
npm ERR! Failed at the btcpayserver.org@1.0.0 build:static script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/p/.npm/_logs/2024-02-08T08_51_24_963Z-debug.log
[Browsersync] Access URLs:
 --------------------------------------
       Local: http://localhost:3002
    External: http://192.168.0.180:3002
 --------------------------------------
          UI: http://localhost:3003
 UI External: http://192.168.0.180:3003
 --------------------------------------
[Browsersync] Serving files from: dist
[Browsersync] Watching files...
🚨  Could not read file /Users/p/Downloads/btcpayserver.org/transifex/download/website.json : Error: ENOENT: no such file or directory, open '/Users/p/Downloads/btcpayserver.org/transifex/download/website.json'
    at Object.openSync (fs.js:497:3)
    at readFileSync (fs.js:393:35)
    at getTransifexJSON (/Users/p/Downloads/btcpayserver.org/tasks/util.js:61:21)
    at getLanguages (/Users/p/Downloads/btcpayserver.org/tasks/util.js:83:17)
    at Object.<anonymous> (/Users/p/Downloads/btcpayserver.org/tasks/render_html.js:12:15)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/Users/p/Downloads/btcpayserver.org/transifex/download/website.json'
}
/Users/p/Downloads/btcpayserver.org/tasks/util.js:85
  return Object.keys(stats).reduce((res, lang) => {
                ^

TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at getLanguages (/Users/p/Downloads/btcpayserver.org/tasks/util.js:85:17)
    at Object.<anonymous> (/Users/p/Downloads/btcpayserver.org/tasks/render_html.js:12:15)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47
npm ERR! code ELIFECYCLE
npm ERR! errno 1
🚨  Could not read file /Users/p/Downloads/btcpayserver.org/transifex/download/video.json : Error: ENOENT: no such file or directory, open '/Users/p/Downloads/btcpayserver.org/transifex/download/video.json'
    at Object.openSync (fs.js:497:3)
    at readFileSync (fs.js:393:35)
    at getTransifexJSON (/Users/p/Downloads/btcpayserver.org/tasks/util.js:61:21)
    at getLanguages (/Users/p/Downloads/btcpayserver.org/tasks/util.js:83:17)
    at Object.<anonymous> (/Users/p/Downloads/btcpayserver.org/tasks/render_vtt.js:5:15)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/Users/p/Downloads/btcpayserver.org/transifex/download/video.json'
}
npm ERR! btcpayserver.org@1.0.0 build:html: `node tasks/render_html.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the btcpayserver.org@1.0.0 build:html script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
/Users/p/Downloads/btcpayserver.org/tasks/util.js:85
  return Object.keys(stats).reduce((res, lang) => {
                ^

TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at getLanguages (/Users/p/Downloads/btcpayserver.org/tasks/util.js:85:17)
    at Object.<anonymous> (/Users/p/Downloads/btcpayserver.org/tasks/render_vtt.js:5:15)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47
npm ERR! code ELIFECYCLE
npm ERR! errno 1

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/p/.npm/_logs/2024-02-08T08_51_25_017Z-debug.log
npm ERR! btcpayserver.org@1.0.0 build:vtt: `node tasks/render_vtt.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the btcpayserver.org@1.0.0 build:vtt script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/p/.npm/_logs/2024-02-08T08_51_25_026Z-debug.log

```

When running `npm init` to try to fix translations I get this

```
p@Pavles-MacBook-Air btcpayserver.org % npm run init

> btcpayserver.org@1.0.0 init /Users/p/Downloads/btcpayserver.org
> npm-run-all clean -p d:*


> btcpayserver.org@1.0.0 clean /Users/p/Downloads/btcpayserver.org
> rimraf dist && mkdir -p dist


> btcpayserver.org@1.0.0 d:contributors /Users/p/Downloads/btcpayserver.org
> node -r dotenv/config tasks/download_contributors.js


> btcpayserver.org@1.0.0 d:translations /Users/p/Downloads/btcpayserver.org
> node -r dotenv/config tasks/download_translations.js && cp transifex/resources/video.json transifex/download/video/en_GB.json && cp transifex/resources/website.json transifex/download/website/en_GB.json

(node:9732) UnhandledPromiseRejectionWarning: TypeError: this.auth is not a function
    at s.request (/Users/p/Downloads/btcpayserver.org/node_modules/@transifex/api/dist/node.transifexApi.js:1:284176)
    at d.fetch (/Users/p/Downloads/btcpayserver.org/node_modules/@transifex/api/dist/node.transifexApi.js:1:281205)
    at d.get (/Users/p/Downloads/btcpayserver.org/node_modules/@transifex/api/dist/node.transifexApi.js:1:282686)
    at Function.get (/Users/p/Downloads/btcpayserver.org/node_modules/@transifex/api/dist/node.transifexApi.js:1:275636)
    at /Users/p/Downloads/btcpayserver.org/tasks/download_translations.js:14:56
    at Object.<anonymous> (/Users/p/Downloads/btcpayserver.org/tasks/download_translations.js:53:3)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:9732) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:9732) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
cp: transifex/download/video/en_GB.json: No such file or directory
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! btcpayserver.org@1.0.0 d:translations: `node -r dotenv/config tasks/download_translations.js && cp transifex/resources/video.json transifex/download/video/en_GB.json && cp transifex/resources/website.json transifex/download/website/en_GB.json`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the btcpayserver.org@1.0.0 d:translations script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/p/.npm/_logs/2024-02-08T08_54_10_703Z-debug.log
ERROR: "d:translations" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! btcpayserver.org@1.0.0 init: `npm-run-all clean -p d:*`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the btcpayserver.org@1.0.0 init script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/p/.npm/_logs/2024-02-08T08_54_10_758Z-debug.log
```

**Comment by pavlenex** [comment]
@dennisreimann if you have any ideas how to fix this let me know what I may be doing wrong 🤷

**Comment by pavlenex** [comment]
Alright, @dennisreimann helped me figure this one out, as the readme in prerequisites say, for transifex to work there needs to be .env file created in root with this line Otherwise use TRANSIFEX_TOKEN="yourtransifextokenhere"
